/**
 * This class file was automatically generated by jASN1 v1.9.1-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.openiec61850.internal.mms.asn1;

import org.openmuc.jasn1.ber.types.string.*;

public class BasicIdentifier extends BerVisibleString {

    private static final long serialVersionUID = 1L;

    public BasicIdentifier() {
    }

    public BasicIdentifier(byte[] value) {
        super(value);
    }

}
