/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package org.openmuc.openiec61850.internal.mms.asn1;

import org.openmuc.jasn1.ber.types.BerBitString;

public class ParameterSupportOptions extends BerBitString {

    private static final long serialVersionUID = 1L;

    public ParameterSupportOptions() {
    }

    public ParameterSupportOptions(byte[] code) {
        super(code);
    }

    public ParameterSupportOptions(byte[] value, int numBits) {
        super(value, numBits);
    }

    public ParameterSupportOptions(boolean[] value) {
        super(value);
    }

}
