/** This class file was automatically generated by jASN1 v1.9.1-SNAPSHOT (http://www.openmuc.org) */
package org.openmuc.openiec61850.internal.mms.asn1;

import org.openmuc.jasn1.ber.types.BerBitString;

public class ServiceSupportOptions extends BerBitString {

  private static final long serialVersionUID = 1L;

  public ServiceSupportOptions() {}

  public ServiceSupportOptions(byte[] code) {
    super(code);
  }

  public ServiceSupportOptions(byte[] value, int numBits) {
    super(value, numBits);
  }

  public ServiceSupportOptions(boolean[] value) {
    super(value);
  }
}
