/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package org.openmuc.openiec61850.internal.mms.asn1;

import java.math.BigInteger;

import org.openmuc.jasn1.ber.types.BerInteger;

public class Unsigned16 extends BerInteger {

    private static final long serialVersionUID = 1L;

    public Unsigned16() {
    }

    public Unsigned16(byte[] code) {
        super(code);
    }

    public Unsigned16(BigInteger value) {
        super(value);
    }

    public Unsigned16(long value) {
        super(value);
    }

}
