/**
 * This class file was automatically generated by jASN1 v1.9.1-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.openiec61850.internal.mms.asn1;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class Unsigned32 extends BerInteger {

	private static final long serialVersionUID = 1L;

	public Unsigned32() {
	}

	public Unsigned32(byte[] code) {
		super(code);
	}

	public Unsigned32(BigInteger value) {
		super(value);
	}

	public Unsigned32(long value) {
		super(value);
	}

}
