/**
 * This class file was automatically generated by jASN1 v1.9.1-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.openiec61850.internal.mms.asn1;

import java.math.BigInteger;

import org.openmuc.jasn1.ber.types.BerInteger;

public class Unsigned8 extends BerInteger {

    private static final long serialVersionUID = 1L;

    public Unsigned8() {
    }

    public Unsigned8(byte[] code) {
        super(code);
    }

    public Unsigned8(BigInteger value) {
        super(value);
    }

    public Unsigned8(long value) {
        super(value);
    }

}
