/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.josistack.internal.acse.asn1;

import com.beanit.jasn1.ber.types.BerObjectIdentifier;

public class AETitleForm2 extends BerObjectIdentifier {

  private static final long serialVersionUID = 1L;

  public AETitleForm2() {}

  public AETitleForm2(byte[] code) {
    super(code);
  }

  public AETitleForm2(int[] value) {
    super(value);
  }
}
