/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.josistack.internal.acse.asn1;

import com.beanit.jasn1.ber.types.BerInteger;
import java.math.BigInteger;

public class APInvocationIdentifier extends BerInteger {

  private static final long serialVersionUID = 1L;

  public APInvocationIdentifier() {}

  public APInvocationIdentifier(byte[] code) {
    super(code);
  }

  public APInvocationIdentifier(BigInteger value) {
    super(value);
  }

  public APInvocationIdentifier(long value) {
    super(value);
  }
}
