/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.josistack.internal.acse.asn1;

import com.beanit.jasn1.ber.types.BerObjectIdentifier;

public class ApplicationContextName extends BerObjectIdentifier {

  private static final long serialVersionUID = 1L;

  public ApplicationContextName() {}

  public ApplicationContextName(byte[] code) {
    super(code);
  }

  public ApplicationContextName(int[] value) {
    super(value);
  }
}
