/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.josistack.internal.acse.asn1;

import com.beanit.asn1bean.ber.types.string.BerGraphicString;

public class ImplementationData extends BerGraphicString {

  private static final long serialVersionUID = 1L;

  public ImplementationData() {}

  public ImplementationData(byte[] value) {
    super(value);
  }
}
