/** This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org) */
package com.beanit.josistack.internal.acse.asn1;

import org.openmuc.jasn1.ber.types.BerObjectIdentifier;

public final class OidValues {
  public static final BerObjectIdentifier aCSEId =
      new BerObjectIdentifier(new int[] {2, 2, 3, 1, 1});
  public static final BerObjectIdentifier acseAsId =
      new BerObjectIdentifier(new int[] {2, 2, 1, 0, 1});
}
