/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.josistack.internal.acse.asn1;

import com.beanit.jasn1.ber.types.BerInteger;
import java.math.BigInteger;

public class ReleaseRequestReason extends BerInteger {

  private static final long serialVersionUID = 1L;

  public ReleaseRequestReason() {}

  public ReleaseRequestReason(byte[] code) {
    super(code);
  }

  public ReleaseRequestReason(BigInteger value) {
    super(value);
  }

  public ReleaseRequestReason(long value) {
    super(value);
  }
}
