/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.openiec61850.internal.mms.asn1;

import com.beanit.jasn1.ber.types.BerInteger;
import java.math.BigInteger;

public class DataAccessError extends BerInteger {

  private static final long serialVersionUID = 1L;

  public DataAccessError() {}

  public DataAccessError(byte[] code) {
    super(code);
  }

  public DataAccessError(BigInteger value) {
    super(value);
  }

  public DataAccessError(long value) {
    super(value);
  }
}
