/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.openiec61850.internal.mms.asn1;

import com.beanit.jasn1.ber.types.BerNull;

public class FileDeleteResponse extends BerNull {

  private static final long serialVersionUID = 1L;

  public FileDeleteResponse() {}

  public FileDeleteResponse(byte[] code) {
    super(code);
  }
}
