/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.openiec61850.internal.mms.asn1;

import java.math.BigInteger;

public class FileCloseRequest extends Integer32 {

  private static final long serialVersionUID = 1L;

  public FileCloseRequest() {}

  public FileCloseRequest(byte[] code) {
    super(code);
  }

  public FileCloseRequest(BigInteger value) {
    super(value);
  }

  public FileCloseRequest(long value) {
    super(value);
  }
}
