/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.openiec61850.internal.mms.asn1;

public class GetNamedVariableListAttributesRequest extends ObjectName {

  private static final long serialVersionUID = 1L;

  public GetNamedVariableListAttributesRequest() {}

  public GetNamedVariableListAttributesRequest(byte[] code) {
    super(code);
  }
}
