/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.openiec61850.internal.mms.asn1;

import com.beanit.jasn1.ber.types.BerInteger;
import java.math.BigInteger;

public class Integer16 extends BerInteger {

  private static final long serialVersionUID = 1L;

  public Integer16() {}

  public Integer16(byte[] code) {
    super(code);
  }

  public Integer16(BigInteger value) {
    super(value);
  }

  public Integer16(long value) {
    super(value);
  }
}
