/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.openiec61850.internal.mms.asn1;

import com.beanit.jasn1.ber.types.string.BerVisibleString;

public class MMSString extends BerVisibleString {

  private static final long serialVersionUID = 1L;

  public MMSString() {}

  public MMSString(byte[] value) {
    super(value);
  }
}
