/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.openiec61850.internal.mms.asn1;

import com.beanit.jasn1.ber.types.BerBitString;

public class ServiceSupportOptions extends BerBitString {

  private static final long serialVersionUID = 1L;

  public ServiceSupportOptions() {}

  public ServiceSupportOptions(byte[] code) {
    super(code);
  }

  public ServiceSupportOptions(byte[] value, int numBits) {
    super(value, numBits);
  }

  public ServiceSupportOptions(boolean[] value) {
    super(value);
  }
}
