/**
 * This class file was automatically generated by jASN1 v1.7.2-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.josistack.internal.presentation.asn1;

import org.openmuc.jasn1.ber.types.BerObjectIdentifier;

public class AbstractSyntaxName extends BerObjectIdentifier {

    public AbstractSyntaxName() {
    }

    public AbstractSyntaxName(byte[] code) {
        super(code);
    }

    public AbstractSyntaxName(int[] value) {
        super(value);
    }

}
