/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package org.openmuc.josistack.internal.presentation.asn1;

public class CallingPresentationSelector extends PresentationSelector {

    private static final long serialVersionUID = 1L;

    public CallingPresentationSelector() {
    }

    public CallingPresentationSelector(byte[] value) {
        super(value);
    }

}
