/**
 * This class file was automatically generated by jASN1 v1.7.2-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.josistack.internal.presentation.asn1;

public class CallingPresentationSelector extends PresentationSelector {

    public CallingPresentationSelector() {
    }

    public CallingPresentationSelector(byte[] value) {
        super(value);
    }

}
