/** This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org) */
package org.openmuc.josistack.internal.presentation.asn1;

public class CalledPresentationSelector extends PresentationSelector {

  private static final long serialVersionUID = 1L;

  public CalledPresentationSelector() {}

  public CalledPresentationSelector(byte[] value) {
    super(value);
  }
}
