/**
 * This class file was automatically generated by jASN1 v1.7.2-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.josistack.internal.presentation.asn1;

import java.math.BigInteger;

import org.openmuc.jasn1.ber.types.BerInteger;

public class PresentationContextIdentifier extends BerInteger {

    public PresentationContextIdentifier() {
    }

    public PresentationContextIdentifier(byte[] code) {
        super(code);
    }

    public PresentationContextIdentifier(BigInteger value) {
        super(value);
    }

    public PresentationContextIdentifier(long value) {
        super(value);
    }

}
