/**
 * This class file was automatically generated by jASN1 v1.7.2-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.josistack.internal.presentation.asn1;

import org.openmuc.jasn1.ber.types.BerOctetString;

public class SimplyEncodedData extends BerOctetString {

    public SimplyEncodedData() {
    }

    public SimplyEncodedData(byte[] value) {
        super(value);
    }

}
