/**
 * This class file was automatically generated by jASN1 v1.7.2-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.josistack.internal.presentation.asn1;

import org.openmuc.jasn1.ber.types.BerObjectIdentifier;

public class TransferSyntaxName extends BerObjectIdentifier {

    public TransferSyntaxName() {
    }

    public TransferSyntaxName(byte[] code) {
        super(code);
    }

    public TransferSyntaxName(int[] value) {
        super(value);
    }

}
