/**
 * This class file was automatically generated by jASN1 v1.7.2-SNAPSHOT (http://www.openmuc.org)
 */

package org.openmuc.josistack.internal.presentation.asn1;

import org.openmuc.jasn1.ber.types.BerBitString;

public class UserSessionRequirements extends BerBitString {

    public UserSessionRequirements() {
    }

    public UserSessionRequirements(byte[] code) {
        super(code);
    }

    public UserSessionRequirements(byte[] value, int numBits) {
        super(value, numBits);
    }

}
