/** This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org) */
package org.openmuc.josistack.internal.acse.asn1;

import java.math.BigInteger;
import org.openmuc.jasn1.ber.types.BerInteger;

public class AEInvocationIdentifier extends BerInteger {

  private static final long serialVersionUID = 1L;

  public AEInvocationIdentifier() {}

  public AEInvocationIdentifier(byte[] code) {
    super(code);
  }

  public AEInvocationIdentifier(BigInteger value) {
    super(value);
  }

  public AEInvocationIdentifier(long value) {
    super(value);
  }
}
