/** This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org) */
package org.openmuc.josistack.internal.acse.asn1;

import org.openmuc.jasn1.ber.types.BerObjectIdentifier;

public class ApplicationContextName extends BerObjectIdentifier {

  private static final long serialVersionUID = 1L;

  public ApplicationContextName() {}

  public ApplicationContextName(byte[] code) {
    super(code);
  }

  public ApplicationContextName(int[] value) {
    super(value);
  }
}
