/** This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org) */
package com.beanit.josistack.internal.presentation.asn1;

public class PresentationContextDefinitionResultList extends ResultList {

  private static final long serialVersionUID = 1L;

  public PresentationContextDefinitionResultList() {}

  public PresentationContextDefinitionResultList(byte[] code) {
    super(code);
  }
}
