/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.josistack.internal.presentation.asn1;

import com.beanit.jasn1.ber.types.BerOctetString;

public class PresentationSelector extends BerOctetString {

  private static final long serialVersionUID = 1L;

  public PresentationSelector() {}

  public PresentationSelector(byte[] value) {
    super(value);
  }
}
