/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.josistack.internal.presentation.asn1;

import com.beanit.jasn1.ber.types.BerBitString;

public class ProtocolVersion extends BerBitString {

  private static final long serialVersionUID = 1L;

  public ProtocolVersion() {}

  public ProtocolVersion(byte[] code) {
    super(code);
  }

  public ProtocolVersion(byte[] value, int numBits) {
    super(value, numBits);
  }

  public ProtocolVersion(boolean[] value) {
    super(value);
  }
}
