/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.josistack.internal.presentation.asn1;

public class RespondingPresentationSelector extends PresentationSelector {

  private static final long serialVersionUID = 1L;

  public RespondingPresentationSelector() {}

  public RespondingPresentationSelector(byte[] value) {
    super(value);
  }
}
