/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.josistack.internal.presentation.asn1;

import com.beanit.asn1bean.ber.types.BerObjectIdentifier;

public class TransferSyntaxName extends BerObjectIdentifier {

  private static final long serialVersionUID = 1L;

  public TransferSyntaxName() {}

  public TransferSyntaxName(byte[] code) {
    super(code);
  }

  public TransferSyntaxName(int[] value) {
    super(value);
  }
}
