/** This class file was automatically generated by jASN1 (http://www.beanit.com) */
package com.beanit.josistack.internal.presentation.asn1;

import com.beanit.jasn1.ber.types.BerBitString;

public class UserSessionRequirements extends BerBitString {

  private static final long serialVersionUID = 1L;

  public UserSessionRequirements() {}

  public UserSessionRequirements(byte[] code) {
    super(code);
  }

  public UserSessionRequirements(byte[] value, int numBits) {
    super(value, numBits);
  }

  public UserSessionRequirements(boolean[] value) {
    super(value);
  }
}
