/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.iec61850bean.internal.mms.asn1;

import com.beanit.asn1bean.ber.types.BerInteger;
import java.math.BigInteger;

public class DataAccessError extends BerInteger {

  private static final long serialVersionUID = 1L;

  public DataAccessError() {}

  public DataAccessError(byte[] code) {
    super(code);
  }

  public DataAccessError(BigInteger value) {
    super(value);
  }

  public DataAccessError(long value) {
    super(value);
  }
}
