/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.iec61850bean.internal.mms.asn1;

import com.beanit.asn1bean.ber.types.BerNull;

public class FileDeleteResponse extends BerNull {

  private static final long serialVersionUID = 1L;

  public FileDeleteResponse() {}

  public FileDeleteResponse(byte[] code) {
    super(code);
  }
}
