/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.iec61850bean.internal.mms.asn1;

public class FileDeleteRequest extends FileName {

  private static final long serialVersionUID = 1L;

  public FileDeleteRequest() {}

  public FileDeleteRequest(byte[] code) {
    super(code);
  }
}
