/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.iec61850bean.internal.mms.asn1;

public class InitiateErrorPDU extends ServiceError {

  private static final long serialVersionUID = 1L;

  public InitiateErrorPDU() {}

  public InitiateErrorPDU(byte[] code) {
    super(code);
  }
}
