/*
 * This class file was automatically generated by ASN1bean (http://www.beanit.com)
 */

package com.beanit.iec61850bean.internal.mms.asn1;

import com.beanit.asn1bean.ber.types.string.BerVisibleString;

public class MMSString extends BerVisibleString {

  private static final long serialVersionUID = 1L;

  public MMSString() {}

  public MMSString(byte[] value) {
    super(value);
  }
}
